default_platform(:ios)

platform :ios do
  desc "Build the app"
  lane :build do
    build_app(
      workspace: "App.xcworkspace",
      scheme: "App",
      export_method: "app-store"
    )
  end
end
